### ISSUE TITLE
Missing weights file for DenseNet

### ISSUE THREAD

**Issue by q-langfitt** [FVL2020/2DImageBMIestimationEnd2End#1]
It appears that the weights file for the DenseNet is missing, as I ran into the following error: 

FileNotFoundError: [Errno 2] No such file or directory: 'SEDensenet121_3CWithMask_2048-1-batch_32/model_epoch_50.ckpt'

Could you add the weights to the repo? Or if you think this is an error on my end, I'd appreciate any suggestions you may have for resolving the issue.

**Comment by LL3RD** [comment]
Thanks for your reminder, we have modified the training file so that it can be trained without pretrained model. And you can also test with our provided checkpoint from google drive.
